config/routes.rb
Rails.application.routes.draw do
  resources :campaign_members
  root to: "home#index"
  get 'home/index'
  #devise_for :users
  #for whatever reason, redirection to the root doesn't work when signing up, so I have to make a new controller etc.
  devise_for :users, controllers: { registrations: "registrations" }
  #resources :useful_links
  resources :campaigns do
      resources :notes, :useful_links, :campaign_members
  end
  #resources :notes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/note.rb
class Note < ApplicationRecord
    #has_rich_text :content
    has_rich_text :content
    belongs_to :user
    belongs_to :campaign

    validates :note_heading, presence: true
    validates :content, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :get_campaign
  before_action :set_note, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /notes or /notes.json
  def index
    #@notes = Note.all
    @notes = @campaign.notes
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    #@note = Note.new
    #@note = current_user.notes.build
    #@note = @campaign.current_user.notes.build
    #@note = current_user.@campaign.notes.build
    @note = @campaign.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    #@note = Note.new(note_params)
    #@note = @campaign.current_user.notes.build(note_params)
    @note = @campaign.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("campaign-notes-list", partial: "notes/note", locals: {note: @note})
        end
        #format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.html { redirect_to campaign_path(@campaign), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("campaign-notes-list", partial: "notes/note", locals: {note: @note})
        end
        #format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.html { redirect_to campaign_path(@campaign), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      #format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      #format.html { redirect_to campaign_path(@campaign), notice: "Note was successfully destroyed." }
      format.html { redirect_to campaign_notes_path(@campaign), notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private
    def correct_user
      @note = current_user.notes.find_by(id: params[:id])
      redirect_to campaign_notes_path, notice: "Not authorized!" if @note.nil?
    end
    def get_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end
    
    def set_note
      @note = @campaign.notes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:user_id, :campaign_id, :note_text, :content, :note_heading, :audience, :category)
      #params.require(:note).permit(:user_id, :campaign_id, :content)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="z-modal-form">
  <%= form_with(model: [@campaign, note]) do |form| %>
    <% if note.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
          <% note.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.number_field :user_id, id: :note_user_id, value: current_user.id, type: :hidden %>
    <div>
      <%= form.label :audience, style: "display: block" %>
      <%= form.select :audience, [ ["All Members"],["Selected Members"],["Private"]]  %>
    </div>
    <div>
      <%= form.label :category, style: "display: block" %>
      <%= form.select :category, [ ["Session"],["NPC"],["House Rule"],["Plot"] ]%>
    </div>
    <div>
      <%= form.label :note_heading, style: "display: block" %>
      <%= form.text_field :note_heading, placeholder: "Note title" %>
    </div>
    <div>
      <%= form.label :content %>
      <%= form.rich_text_area :content %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/notes/_note.html.erb
<li class="note-item" data-category="<%=note.category%>" id="<%= dom_id note%>">
  <h4><%= note.note_heading %></h4>
  <div class="trix-override"><%= note.content %></div>
  <% if note.user_id == current_user.id %>
    <%= link_to "(Edit", edit_campaign_note_path(@campaign, note), data:{turbo_frame: "modalForm", controller: "turbomodal", action: "turbomodal#showModal"} %>|<%= link_to "Delete)", [@campaign, note], data: {turbo_method: :delete, turbo_confirm: "Delete note?"} %>
  <% end %>
</li>

app/views/notes/edit.html.erb
<%= turbo_frame_tag :modalForm do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd" id="theModal">
    <div class="z-modal-header">
      <div class="z-modal-left-side-item">
        <h1>Editing note</h1>
      </div>
      <div class="z-modal-close-button right-side-item" data-controller="turbomodal" data-action="click->turbomodal#modalClose">&times;</div>
    </div>
    <%= render "form", note: @note %>
  </div>
<% end %>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <div>
      <span><%= note.note_heading%></span>
      <% if note.category%>
        <span><%=note.category%></span>
      <% end %>
      <% if note.audience %>
        <span><%= note.audience%></span>
      <% end %>
      <div class="trix-override">
        <%= note.content %>
      </div>
    <div>
      <%= link_to "(Edit", edit_campaign_note_path(@campaign, note)%>|<%= link_to "Delete)", [@campaign, note], data: {turbo_method: :delete, turbo_confirm: "Delete note?"} %>
    </div>
  <% end %>
  <%= link_to "Back to Campaign", campaign_path(@campaign) %>
</div>

app/views/notes/new.html.erb
<%= turbo_frame_tag :modalForm do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd" id="theModal">
    <div class="z-modal-header">
      <div class="z-modal-left-side-item">
        <h1>New note</h1>
      </div>
      <div class="z-modal-close-button right-side-item" data-controller="turbomodal" data-action="click->turbomodal#modalClose">&times;</div>
    </div>
    <%= render "form", note: @note %>
  </div>
<% end %>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>