config/routes.rb
Rails.application.routes.draw do
  resources :campaign_members
  root to: "home#index"
  get 'home/index'
  #devise_for :users
  #for whatever reason, redirection to the root doesn't work when signing up, so I have to make a new controller etc.
  devise_for :users, controllers: { registrations: "registrations" }
  #resources :useful_links
  resources :campaigns do
      resources :notes, :useful_links, :campaign_members
  end
  #resources :notes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @campaigns = Campaign.left_outer_joins(:campaign_members).select("distinct campaigns.*").where("campaign_members.user_id=? or campaigns.user_id=?",current_user.id,current_user.id)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_menubar.html.erb
<%= javascript_include_tag "custom/btn_test2"%>
<div>
  <nav class="top-bar topbar-responsive">
    <div class="top-bar-title">
      <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
        <button id="flipFlop" class="menu-icon" type="button" onclick="doot()" data-toggle></button>
      </span>
      <%= link_to home_index_path,class:"topbar-responsive-logo" do %>
        <strong>DND Notes</strong>
      <% end %>
    </div>
    <div id="topbar-responsive" class="topbar-responsive-links">
      <div class="top-bar-right">
        <ul class="menu simple vertical medium-horizontal">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete} %>
            <li><%= link_to current_user.user_name + " (Edit profile)", edit_user_registration_path %></li>
            <li><%= link_to "Campaigns", campaigns_path %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/home/index.html.erb
    <% if user_signed_in? %>
        <% if @campaigns.each do |campaign| %>
          <div id="<%= dom_id campaign %>" class="blockquote-container">
            <div class="callout">
              <h4 class="blockquote-title"><%= link_to campaign.name, campaign %>
                <% if campaign.user_id == current_user.id %>
                   (owner)
                <% else %>
                   (member)
                <% end %>
              </h4>
            </div>
          </div>
        <% end.empty? %>
          <p>You have no campaigns created.</p>
          <%= link_to "Create one!", new_campaign_path %>
        <% end %>
    <% else %>
      <h2>DND Helpy McHelperton tool</h2>
      <p>This here thingy allows you to put in notes and links associated with a campaign. I used to use OneNote for this, but I don't want to use dumb microsoft cloud thingy, so those notes were trapped on a computer... Look, it just became a pain.</p>
      <p>I'm hoping this allow me to better organize stuff. And I'd like to expand it to include the ability to add non-campaign owners to the mix so they can both make personal notes as well as see DM notes, etc. We'll see.</p>
      <p>To use this, you have to sign up. You do not even need to use a real email, but you'll need to remember the fake email address you provide to get back to your data.</p>
      <p>I hope you enjoy</p>
    <% end %>