config/routes.rb
Rails.application.routes.draw do
  resources :campaign_members
  root to: "home#index"
  get 'home/index'
  #devise_for :users
  #for whatever reason, redirection to the root doesn't work when signing up, so I have to make a new controller etc.
  devise_for :users, controllers: { registrations: "registrations" }
  #resources :useful_links
  resources :campaigns do
      resources :notes, :useful_links, :campaign_members
  end
  #resources :notes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/campaign.rb
class Campaign < ApplicationRecord
    belongs_to :user
    has_many :notes, dependent: :destroy
    has_many :useful_links, dependent: :destroy
    has_many :campaign_members, dependent: :destroy
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /campaigns or /campaigns.json
  def index
    #@campaigns = Campaign.all
    #@campaigns = current_user.campaigns.all.order(name: :asc)
    @campaigns = Campaign.left_outer_joins(:campaign_members).where("campaigns.user_id=? or campaign_members.user_id=?",current_user.id,current_user.id).select("distinct campaigns.*")
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
    @testVal = @campaign.notes.distinct.select("category")
    @notes = Note.joins(:campaign).where("campaigns.id=? and (notes.user_id=? or notes.audience =?)",@campaign.id,current_user.id,"All Members").select("notes.*").order("notes.created_at DESC")
    #@links = current_user.useful_links.joins(:campaign).order("useful_links.name")
    #@links = UsefulLink.campaign.current_user.order("useful_links.name")
    @links = UsefulLink.joins(:campaign).where("campaigns.id=? and useful_links.user_id=?",@campaign.id,current_user.id)
  end

  # GET /campaigns/new
  def new
    #@campaign = Campaign.new
    @campaign = current_user.campaigns.build
  end

  # GET /campaigns/1/edit
  def edit
    #@campaign = Campaign.find(params[:id])
  end

  # POST /campaigns or /campaigns.json
  def create
    #@campaign = Campaign.new(campaign_params)
    @campaign = current_user.campaigns.build(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
        #format.html { redirect_to @campaign, notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      #@campaign = Campaign.find(params[:id])

      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully updated." }
        #format.html { redirect_to @campaign, notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    #@campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      #format.html { redirect_to campaigns_url, notice: "Campaign was successfully destroyed." }
      format.html { redirect_to "root_path", notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  


  private
    
    def correct_user  
      @campaignCheck = current_user.campaigns.find_by(id: params[:id])
      #redirect_to campaigns_path, notice: "Not authorized!" if @campaignCheck.nil?
      redirect_to campaign_url(@campaign), notice: "Not authorized!" if @campaignCheck.nil?
    end

    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :name)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>" class="blockquote-container">
    <div class="callout">
      <h4 class="blockquote-title"><%= link_to campaign.name, campaign %></h4>
    </div>
</div>

app/views/campaigns/_form.html.erb
<div class="translucent-form-overlay">
  <%= form_with(model: campaign) do |form| %>
    <% if campaign.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

        <ul>
          <% campaign.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h3>create/edit</h3>
    <div>
      <%=form.number_field :user_id, id: :campaign_user_id, value: current_user.id, type: :hidden %>
    </div>

    <div class="row columns">
      <%= form.label :name, style: "display: block" do %>
        <%= form.text_field :name %>
      <% end %>
    </div>

    <div>
      <%= form.submit class:"base-submit-button primary button expanded search-button" %>
    </div>
  <% end %>
</div>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Campaigns</h1>
<%= link_to "New campaign", new_campaign_path %>
<div id="campaigns" class="genFlex">
  <% @campaigns.each do |campaign| %>
    <%= render campaign %>
  <% end %>
</div>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="links">
    <ul id="add-link-list">
      <li class="link-item"><%= link_to "add a link", new_campaign_useful_link_path(@campaign), data:{turbo_frame: "modalForm", controller: "turbomodal", action: "turbomodal#showModal"} %></li>
    </ul>
    <ul id="campaign-links-list">
      <% if @links.each do |link| %>
        <li class="link-item"><a href="<%= link.url %>" target="_blank"><%= link.name %></a></li>
      <% end.empty? %>
        <li class="link-item">No links</li>
      <% end%>
    </ul>
  </div>
  <div class="notes">
    <ul id="add-note-list">
      <li class="note-item"><%= link_to "add a note", new_campaign_note_path(@campaign), data:{turbo_frame: "modalForm", controller: "turbomodal", action: "turbomodal#showModal"} %></li>
    </ul>
    <ul id="campaign-notes-list">
      <% if @notes.each do |note| %>
        <%= render note %>
      <% end.empty? %>
        <li class="note-item">No notes</li>
      <% end %>
  </div>
  <div class="utility">
    <ul class="utility-list">
      <h2><%= @campaign.name%></h2>
      <li><%= link_to "Campaign edit", edit_campaign_path(@campaign)%></li>
      <li><%= link_to "Delete campaign", @campaign, data: {turbo_method: :delete, turbo_confirm: "For realsies?"} %></li>
      <li><%= link_to "Campaign members", campaign_campaign_members_path(@campaign) %></li>
    <ul>
  </div>
</div>