config/routes.rb
Rails.application.routes.draw do
  resources :campaign_members
  root to: "home#index"
  get 'home/index'
  #devise_for :users
  #for whatever reason, redirection to the root doesn't work when signing up, so I have to make a new controller etc.
  devise_for :users, controllers: { registrations: "registrations" }
  #resources :useful_links
  resources :campaigns do
      resources :notes, :useful_links, :campaign_members
  end
  #resources :notes
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/campaign_member.rb
class CampaignMember < ApplicationRecord
  belongs_to :campaign
  belongs_to :user
end

app/controllers/campaign_members_controller.rb
class CampaignMembersController < ApplicationController
  before_action :get_campaign
  before_action :set_campaign_member, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :create]

  # GET /campaign_members or /campaign_members.json
  def index
    #@campaign_members = @campaign.campaign_members.where("campaigns.user_id=?",current_user.id)
    #@campaign_members = @campaign.campaign_members.where("campaign_members.user_id=?",current_user.id)
    #@campaign_members = @campaign.campaign_members.where()
    @campaign_members = @campaign.campaign_members
  end

  # GET /campaign_members/1 or /campaign_members/1.json
  def show
  end

  # GET /campaign_members/new
  def new
    #@campaign_member = CampaignMember.new
    #@userList = users.select("users.email,users.id").joins("left join campaign_members on users.id=campaign_members.user_id").where("campaign_members.user_id is null")
    #@userList = Users.all.joins("left join campaign_members on Users.id=campaign_members.user_id").where("campaign_members.user_id is null").select("Users.email,Users.id")
    #@userList = User.left_outer_joins(:campaign_members).select("distinct users.email,users.id").where("campaign_members.user_id is null")
    @userList = User.left_outer_joins(:campaign_members).select("distinct users.email,users.id").where("campaign_members.campaign_id is null or campaign_members.campaign_id<>?",@campaign.id)
    @campaign_member = @campaign.campaign_members.build
  end

  # GET /campaign_members/1/edit
  def edit
  end

  # POST /campaign_members or /campaign_members.json
  def create
    #@campaign_member = CampaignMember.new(campaign_member_params)
    @campaign_member = @campaign.campaign_members.build(campaign_member_params)

    respond_to do |format|
      if @campaign_member.save
        #format.html { redirect_to campaign_member_url(@campaign_member), notice: "Campaign member was successfully created." }
        format.html { redirect_to campaign_path(@campaign), notice: "Campaign member was successfully created." }
        format.json { render :show, status: :created, location: @campaign_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_members/1 or /campaign_members/1.json
  def update
    respond_to do |format|
      if @campaign_member.update(campaign_member_params)
        #format.html { redirect_to campaign_member_url(@campaign_member), notice: "Campaign member was successfully updated." }
        format.html { redirect_to campaigh_path(@campaign), notice: "Campaign member was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_members/1 or /campaign_members/1.json
  def destroy
    @campaign_member.destroy

    respond_to do |format|
      #format.html { redirect_to campaign_members_url, notice: "Campaign member was successfully destroyed." }
      format.html { redirect_to campaign_campaign_members_path(@campaign), notice: "Campaign member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def get_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end
    def correct_user  
      #only the owner of the campaign can update the campaign members - this check should be based on the campaign itself
      @campaignCheck = current_user.campaigns.find_by(id: @campaign.id)
      #send back to the campaign
      #redirect_to campaign_campaign_members_path, notice: "Not authorized!" if @campaignCheck.nil?
      redirect_to campaign_url(@campaign), notice: "Not authorized!" if @campaignCheck.nil?
    end


    def set_campaign_member
      @campaign_member = @campaign.campaign_members.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_member_params
      params.require(:campaign_member).permit(:user_id, :campaign_id)
    end
end

app/helpers/campaign_members_helper.rb
module CampaignMembersHelper
end

app/views/campaign_members/_campaign_member.html.erb
<div id="<%= dom_id campaign_member %>">
  <p>
    <strong>User:</strong>
    <%= campaign_member.user.email + "(" + campaign_member.user_name + ")" %>
  </p>

  <p>
    <strong>Campaign:</strong>
    <%= campaign_member.campaign_id %>
  </p>

</div>

app/views/campaign_members/_form.html.erb
<%#= form_with(model: campaign_member) do |form| %>
<%= form_with(model: [@campaign, campaign_member]) do |form| %>
  <% if campaign_member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign_member.errors.count, "error") %> prohibited this campaign_member from being saved:</h2>

      <ul>
        <% campaign_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%#= form.text_field :user_id %>
    <%= form.select :user_id, @userList.map { |u| [u.email, u.id]} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaign_members/edit.html.erb
<h1>Editing campaign member</h1>

<%= render "form", campaign_member: @campaign_member %>

<br>

<div>
  <%= link_to "Back to campaign", campaign_path(@campaign) %>
</div>

app/views/campaign_members/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @campaign.name %> members</h1>

<div id="campaign_members">
  <ul class="campaign-members-list">
    <% if @campaign_members.each do |campaign_member| %>
      <li>
        <%#= User.find_by(id: campaign_member.user_id).email + "(" + User.find_by(id: campaign_member.user_id).user_name + ")" %>
        <%= campaign_member.user.email + "(" + campaign_member.user.user_name + ")" %>
        <p>
          <%#= link_to "Show this campaign member", campaign_member %>
          <%= link_to "(Edit", edit_campaign_campaign_member_path(@campaign, campaign_member)%>|<%= link_to "Delete)", [@campaign, campaign_member], data: {turbo_method: :delete, turbo_confirm: "Delete member?"} %>
        </p>
      </li>
    <% end.empty? %>  
      <li>No members added</li>
    <% end %>
    
  
</div>

<%= link_to "New campaign member", new_campaign_campaign_member_path(@campaign) %>

app/views/campaign_members/new.html.erb
<h1>New campaign member</h1>

<%= render "form", campaign_member: @campaign_member %>

<br>

<div>
  <%= link_to "Back", campaign_campaign_members_path(@campaign) %>
</div>

app/views/campaign_members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campaign_member %>